# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Vagrant-managed VM with Kontain KM / KKM preinstalled.
#

Vagrant.configure(2) do |config|

  config.vm.box = "bento/ubuntu-20.10"

  config.vm.provision "file", source: "../../build/kkm.run", destination: "/tmp/kontain/"
  config.vm.provision "file", source: "./daemon.json", destination: "/tmp/kontain/"
  #   config.vm.network "forwarded_port", guest: 8080, host: 8080

  # find out Kontain version (it can be defined in env)
  kontain_release=ENV['KM_VAGRANT_KM_RELEASE']
  if kontain_release == nil then
    kontain_release="" # use default as provided by km-releases/default-release file in master branch
  end

  config.vm.provision "shell", inline: <<-SHELL

   # Install KKM... it will also validate hardware.
   sudo apt-get install linux-headers-$(uname -r) -y 2>&1
   /tmp/kontain/kkm.run 2>&1

   # Install Docker
   sudo apt-get install -q -y \
         apt-transport-https ca-certificates \
         curl gnupg-agent software-properties-common
   curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - 2>&1

   sudo add-apt-repository \
      "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

   sudo apt-get update -y -q
   sudo apt-get install -y -q docker-ce docker-ce-cli containerd.io

   # Install Kontain.
   sudo mkdir -p /opt/kontain ; sudo chown -R $(whoami) /opt/kontain
   wget https://raw.githubusercontent.com/kontainapp/km-releases/master/kontain-install.sh -q
   chmod a+x ./kontain-install.sh; ./kontain-install.sh #{kontain_release} && rm kontain-install.sh
   echo "PATH=\$PATH:/opt/kontain/bin" >> ~vagrant/.bashrc

   # Add gdb , we usually need it
   sudo apt-get install gdb -y -q

   # Configure Docker and restart
   sudo usermod -aG docker vagrant
   sudo cp /tmp/kontain/daemon.json /etc/docker/daemon.json
   sudo systemctl reload-or-restart docker.service

   # clean up, out of paranoya
   rm -rf /tmp/kontain

  SHELL

   l=ENV['KM_VAGRANT_PRELOAD_IMAGES']
   if l != nil then
      l.split.each do |image|
         config.vm.provision "shell", inline: "docker pull #{image}"
      end
   end

   config.vm.provider "virtualbox" do |v|
      v.memory = 8182
      v.cpus = 4
   end

   config.vm.post_up_message = "Welcome to Ubuntu with Kontain / KKM preinstalled."
end
