#
# sitecustomize file for KM.
# Installed in site directory as sitecustomize.py.
# Python runs script before main is called which allows us to insert our
# custom MetaPathFinder into the import system.
#
from importlib.abc import MetaPathFinder, Loader
from importlib.util import find_spec
from importlib.machinery import ModuleSpec
import sys


class MyMetaPathFinder(MetaPathFinder):
    def find_spec(self, fullname, path, target=None):
        # module name should be the same as generated by extract_build.py
        module_name = '_KM_{}'.format(fullname.replace('.', '_'))
        if module_name in sys.builtin_module_names:
            return find_spec(module_name)
        return None


sys.meta_path.insert(0, MyMetaPathFinder())
# print('KM Import Hook installed. Known  modules: ', sys.builtin_module_names)
