# Copyright © 2019 Kontain Inc. All rights reserved.
#
# Kontain Inc CONFIDENTIAL
#
#  This file includes unpublished proprietary source code of Kontain Inc. The
#  copyright notice above does not evidence any actual or intended publication of
#  such source code. Disclosure of this source code or any related proprietary
#  information is strictly prohibited without the express written permission of
#  Kontain Inc.
#
# sitecustomize file for KM.
# Installed in site directory as sitecustomize.py.
# Python runs script before main is called which allows us to insert our
# custom MetaPathFinder into the import system.
#
from importlib.abc import MetaPathFinder, Loader
from importlib.util import find_spec
from importlib.machinery import ModuleSpec
import sys


class MyMetaPathFinder(MetaPathFinder):
    def find_spec(self, fullname, path, target=None):
        # module name should be the same as generated by extract_build.py
        module_name = '_KM_{}'.format(fullname.replace('.', '_'))
        #print("fullname=", fullname, " module_name= ", module_name, " path=", path)
        if module_name in sys.builtin_module_names:
            # print("*match*")
            return find_spec(module_name)
        return None


sys.meta_path.insert(0, MyMetaPathFinder())
# print('KM Import Hook installed. Known  modules: ', sys.builtin_module_names)
