# Kontain pipeline
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:

- stage: Buildenv

  jobs:

  - template: azure-pipelines-km-buildenv-template.yml
    parameters:
      name: 'fedora'

  - template: azure-pipelines-km-buildenv-template.yml
    parameters:
      name: 'ubuntu'

  - template: azure-pipelines-km-buildenv-template.yml
    parameters:
      name: 'alpine'

- stage: Build

  jobs:

  - template: azure-pipelines-km-build-template.yml
    parameters:
      name: 'fedora'

  - template: azure-pipelines-km-build-template.yml
    parameters:
      name: 'ubuntu'

- stage: 'Test'
  jobs:
  - job: test
 
