#
# Kontain Monitor Azure Pipeline definition
#
# A pipeline to automate the release process outlined under `./doc/release.md`.
name: release-$(BuildID) $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  tags:
    include:
      - v*

pr: none

jobs:
  - job: release_automation
    variables:
      vmImage: "ubuntu-20.04"
      buildenv_image_version: latest # use this for all buildenv containers
      image_version: ci-$(Build.BuildId) # use this for all other containers
      # trace: true # uncomment to enable '-x' in all bash scripts

    # Default job has a 60 minutes timeout. Sets this to 0 to use the max
    # 360 minutes timeout.
    timeoutInMinutes: "0"

    pool:
      vmImage: $(vmImage)

    steps:
      - template: templates/setup.yaml

      - template: templates/build.yaml

      - bash: sudo make -C km release -d
        displayName: build release tarball

      - bash: make -C km push_release GITHUB_RELEASE_TOKEN=$(GITHUB_RELEASE_TOKEN) RELEASE_TAG=$(Build.SourceBranch)
        displayName: push release

      - bash: |
          az logout
        condition: always()
        displayName: logout
