name: ci-nightly-$(BuildID) $(Date:yyyyMMdd)$(Rev:.r)

# Must explicitly opt out of pr and CI trigger.
pr: none
trigger: none

schedules:
- cron: "0 7 * * *"
  displayName: Daily build midnight pacific time (UTC + 7)
  branches:
    include:
    - master

variables:
  VM_IMAGE: "ubuntu-18.04"
  CLUSTER_NAME: "aks-kontain-ci-nightly-$(Build.BuildId)"
  VM_SIZE: "Standard_D4_v3" # choose a vm size to avoid the vcpu quota on azure
  BUILDENV_IMAGE_VERSION: latest # use this for all buildenv containers
  IMAGE_VERSION: ci-nightly-$(Build.BuildId) # use this for all other containers
  # TRACE: true

pool:
  vmImage: $(VM_IMAGE)

steps:
- template: templates/setup.yaml

- template: templates/build.yaml

- bash: cloud/azure/aks_ci_create.sh $(CLUSTER_NAME) $(SP_appId) $(SP_password)
  displayName: Create k8s Cluster

- bash: |
    make -C cloud/k8s/kontaind install
  displayName: deploy and verify kontaind

- template: templates/ci_normal.yaml

- bash: cloud/azure/aks_ci_destroy.sh $(CLUSTER_NAME)
  displayName: Tear down k8s Cluster

- bash: |
    rm -f ~/.kube/config
    az logout
  condition: always()
  displayName: Cleanup and logout
