trigger:
- jme/tests
pr:
- master

variables:
    azureSubscriptionEndpoint: kontainAzureResourceManageServiceConnection
    azureContainerRegistry: kontainkubecr
    azureResourceGroup: kontainKubeRG
    kubernetesCluster: kontainKubeCluster
    registry: 'kontainkubecr.azurecr.io'
    registrySC: 'kontainkubecr_service_connection'
    k8sSC: 'CD-to-k8s'
    vmImage: 'ubuntu-16.04'

pool:
    vmImage: $(vmImage)
    
steps:
- checkout: self
  submodules: true

- task: Docker@2
  displayName: login to $(registrySC)
  inputs:
    command: login
    containerRegistry: $(registrySC)

- bash: echo "##vso[task.setvariable variable=git_rev]$(git rev-parse --short HEAD)"

- script: |
    set -e
    docker pull $(registry)/km-buildenv-fedora
    docker tag $(registry)/km-buildenv-fedora  km-buildenv-fedora
    make withdocker DTYPE=fedora
    echo "short head: $git_rev"
    sed  -i "s:BRANCH_NAME:$(git_rev):"        tests/bats-job.yaml
    sed  -i "s:BUILD_ID:$(Build.BuildId):"     tests/bats-job.yaml
    cat tests/bats-job.yaml
  displayName: build 

- script: |
    set -e
    cp -v build/km/km tests/
    make mk-bats TAG=$(Build.BuildId)
    docker tag test-bats:$(Build.BuildId)  $(registry)/test-bats:$(Build.BuildId)
    docker push $(registry)/test-bats:$(Build.BuildId)
  displayName: dockerize tests

- task: Kubernetes@1
  displayName: start tests
  inputs:
    connectionType: Kubernetes Service Connection
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureResourceGroup: $(azureResourceGroup)
    kubernetesCluster: $(kubernetesCluster)
    kubernetesServiceEndpoint: $(k8sSC)
    command: apply
    arguments: -f tests/bats-job.yaml

- task: Kubernetes@1
  displayName: run tests
  inputs:
    connectionType: Kubernetes Service Connection
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureResourceGroup: $(azureResourceGroup)
    kubernetesCluster: $(kubernetesCluster)
    kubernetesServiceEndpoint: $(k8sSC)
    command: wait
    arguments: --timeout 240s --for=condition=complete job/bats-$(Build.BuildId)

- task: Kubernetes@1
  condition: always()
  displayName: get tests results
  inputs:
    connectionType: Kubernetes Service Connection
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureResourceGroup: $(azureResourceGroup)
    kubernetesCluster: $(kubernetesCluster)
    kubernetesServiceEndpoint: $(k8sSC)
    command: logs
    arguments: jobs/bats-$(Build.BuildId)

- task: Kubernetes@1
  condition: always()
  displayName: delete job bats-$(Build.BuildId)
  inputs:
    connectionType: Kubernetes Service Connection
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureResourceGroup: $(azureResourceGroup)
    kubernetesCluster: $(kubernetesCluster)
    kubernetesServiceEndpoint: $(k8sSC)
    command: delete
    arguments: jobs/bats-$(Build.BuildId)

