name: ci-nightly-$(BuildID) $(Date:yyyyMMdd)$(Rev:.r)

# Must explicitly opt out of pr trigger.
pr: none

schedules:
- cron: "0 7 * * *"
  displayName: Daily build midnight pacific time (UTC + 7)
  branches:
    include:
    - master

variables:
  VM_IMAGE: "ubuntu-18.04"
  CLUSTER_NAME: "aks-kontain-ci-nightly-$(Build.BuildId)"
  # Choose a vm size to avoid the vcpu quota on azure.
  VM_SIZE: "Standard_D2_v3"

pool:
  vmImage: $(VM_IMAGE)

steps:
- template: templates/setup.yaml
- bash: cloud/azure/cluster.sh create $(CLUSTER_NAME) --vmsize $(VM_SIZE)
  displayName: Create k8s Cluster
- bash: cloud/azure/cluster.sh clear $(CLUSTER_NAME)
  displayName: Tear down k8s Cluster
