# Set default parameters
parameters:
  registry: 'kontainkubecr.azurecr.io'
  registrySC: 'kontainkubecr_service_connection'
  vmImage: 'ubuntu-16.04'

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}

  steps:

  - checkout: self
    submodules: true

  - task: Docker@2
    displayName: Login to registry service connection
    inputs:
      command: login
      containerRegistry: ${{ parameters.registrySC }}

  - script: |
      make withdocker DTYPE=${{ parameters.name }}
    displayName: make km with ${{ parameters.name }} REGISTRY= ${{ parameters.registry }}

  - script: |
      set -x
      make distro withdocker  ${{ parameters.name }} REGISTRY= ${{ parameters.registry }}
    condition: and(succeeded(), eq('${{ parameters.name }}', 'fedora'))
    displayName: 'make  distro'

