name: ci-nightly-$(BuildID) $(Date:yyyyMMdd)$(Rev:.r)

# Must explicitly opt out of pr trigger.
pr: none

schedules:
- cron: "0 7 * * *"
  displayName: Daily build midnight pacific time (UTC + 7)
  branches:
    include:
    - master

variables:
  VM_IMAGE: "ubuntu-18.04"
  CLUSTER_NAME: "aks-kontain-ci-nightly-$(Build.BuildId)"
  # Choose a vm size to avoid the vcpu quota on azure.
  VM_SIZE: "Standard_D2_v3"
  # TRACE: true

pool:
  vmImage: $(VM_IMAGE)

steps:
- template: templates/setup.yaml

- bash: cloud/azure/aks_ci_create.sh $(CLUSTER_NAME) $(SP_appId) $(SP_password)
  displayName: Create k8s Cluster

- bash: cloud/azure/aks_ci_destroy.sh $(CLUSTER_NAME)
  displayName: Tear down k8s Cluster

- bash: |
    rm -f ~/.kube/config
    az logout
  condition: always()
  displayName: Cleanup and logout
