# Set default parameters
parameters:
  registry: 'kontainkubecr.azurecr.io'
  registrySC: 'kontainkubecr_service_connection'
  vmImage: 'ubuntu-16.04'

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}

  steps:
  - checkout: self
    submodules: true

  - task: Docker@2
    displayName: Login to registry service connection
    inputs:
      command: login
      containerRegistry: ${{ parameters.registrySC }}

  - script: |
      docker pull ${{ parameters.registry }}/km-buildenv-${{ parameters.name }}
      docker tag  ${{ parameters.registry }}/km-buildenv-${{ parameters.name }} km-buildenv-${{ parameters.name }}
      make withdocker DTYPE=${{ parameters.name }}
    displayName: make km with ${{ parameters.name }}

  - script: |
      set -x
      make distro || true
    condition: and(succeeded(), eq('${{ parameters.name }}', 'fedora'))
    displayName: 'make  distro'

  - script: |
      set -x
      make publish || true
    condition: and(succeeded(), eq('${{ parameters.name }}', 'fedora'))
    displayName: 'make  distro'
