# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# VM with Kontain KM / KKM / tensorflow inference app
#

Vagrant.configure("2") do |config|

   config.vm.box = "kontain/fedora-kkm-beta3"
   config.vm.network "forwarded_port", guest: 5000, host: 5000

   config.vm.provision "file", source: ".", destination: "/home/vagrant/"
   config.vm.provision "file", source: "../../tools/hashicorp/build_tensorflow/tensorflow-2.4.1-cp38-cp38-linux_x86_64.whl", destination: "/home/vagrant/"
   config.vm.provision "file", source: "../../payloads/python/cpython/python.kmd", destination: "/home/vagrant/"
   #   config.vm.network "forwarded_port", guest: 8080, host: 8080

   config.vm.provision "shell", inline: <<-SHELL

   firewall-cmd --add-port=5000/tcp

   pip install setuptools
   pip install -r requirements.txt
   pip install tensorflow-*-linux_x86_64.whl
   cp /usr/lib64/libcrypto.so.1.1.1[a-z] /opt/kontain/alpine-lib/lib/libcrypto.so.1.1
   mv python.kmd /usr/bin/python3.8.km
   mv /usr/bin/python3.8 /usr/bin/python3.8.orig

   ln -sf /opt/kontain/bin/km /usr/bin/python3.8

   SHELL

   config.vm.provider "virtualbox" do |v|
      v.memory = 8182
      v.cpus = 4
   end

   config.vm.provider "libvirt" do |v|
      v.memory = 8182
      v.cpus = 4
   end

   config.vm.post_up_message = "Welcome to Kontain tensorflow app"
end
