apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - entry-point.yaml
  - cm-install-lib.yaml
  - cm-containerd-install.yaml
  - containerd-cfg-get.yaml
  - containerd-cfg-update.yaml
  - containerd-restart.yaml
  - runtime-class.yaml
  - kontain-deploy.yaml

configMapGenerator:
  - name: my-vars
    envs: [.env]
    behavior: create

replacements:
  - source:
      kind: ConfigMap
      name: my-vars
      fieldPath: data.RELEASE_TAG
    targets:
      - select:
          kind: DaemonSet
        fieldPaths:
          - spec.template.spec.containers.[name=node-initializer].env.[name=TAG].value
