# WIP - needed for removing cut-n-paste.
#
# Template for running tests in  Kubernetes.
# We use m4 to replace needed macro. 'Macro' is everything with '()' below.
#
# We use it mainly from tests/Makefile. Example:
# m4 -D NAME=pod-name -D IMAGE=full-image-name -D COMMAND=command-to-run | kubectl apply -f -
#
# e.g.
# IMAGE=kontainkubecr.azurecr.io/test-km-fedora:CI-781
# NAME=test-km-fedora-ci-781
# COMMAND='"run_bats_tests.sh", "--km=/tests/km"'
apiVersion: v1
kind: Pod
metadata:
  name: NAME()
spec:
  containers:
    - name: NAME()
      image: IMAGE()
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
      resources:
        requests:
          devices.kubevirt.io/kvm: "1"
          cpu: "250m"
        limits:
          devices.kubevirt.io/kvm: "1"
          cpu: "1"
      command: [COMMAND()]
  restartPolicy: Never
