apiVersion: serving.knative.dev/v1 # Current version of Knative
kind: Service
metadata:
  name: kontain-knative-autoscale # The name of the app
  namespace: default # The namespace the app will use
spec:
  template:
    metadata:
      annotations:
        # Target 10 in-flight-requests per pod.
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
        - image: docker.io/kontainapp/autoscale:latest
          command: ["/opt/kontain/bin/km", "/opt/kontain/bin/autoscale.km"]
          resources:
            # Need kvm device for kontain monitor
            requests:
              devices.kubevirt.io/kvm: "1"
            limits:
              devices.kubevirt.io/kvm: "1"
