apiVersion: apps/v1
kind: Deployment
metadata:
  name: pykm-deployment
  labels:
    app: pykm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pykm
  template:
    metadata:
      labels:
        app: pykm
    spec:
      containers:
      - name: pykm
        image: python-km
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
           requests:
              devices.kubevirt.io/kvm: "1"
              cpu: 100m
              memory: "10Mi"
           limits:
              devices.kubevirt.io/kvm: "1"
              cpu: 2
              memory: "500Mi"
        args: [ "/scripts/micro_srv.py", "8080"]
        volumeMounts:
            - name: kontain-monitor
              mountPath: /opt/kontain
      volumes:
        - name: kontain-monitor
          hostPath:
            path: /opt/kontain
