on:
  workflow_call:
    inputs:
      public-keys-dir:
        description: Directory containing ssh keys
        required: true
    # Map the workflow outputs to job outputs
    outputs:
      runs-on:
        description: Array of referenses to cloud runners
        value: ${{ jobs.start-runners.outputs.runs-on }}

jobs:
  # starts self-hosted runner in AWS and Azure. They are NOT ephemeral and will run until cleanup in the stop-runner
  start-runners:
    name: Start cloud runners
    runs-on: ubuntu-latest
    outputs:
      run-ons: ${{ steps.start-cloud-runner.outputs.run-ons }}
    steps:
      - name: Get public Keys
        uses: actions/checkout@v2

      - name: Start Cloud runners
        id: start-cloud-runner
        uses: kontainapp/cloud-github-runner@v3.1
        with:
          mode: start
          github-token: ${{ secrets.GH_TOKEN }}
          runner-user: kontain
          subnet: "10.0.0.0"
          public-keys-dir: ${{ github.workspace }}/cloud/ssh
          ec2-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          ec2-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ec2-region: "us-east-2"
          ec2-image: "L0BaseImage"
          ec2-instance-type: "m5.xlarge"
          ec2-vpc-name: "github-runner"
          az-subscription-id: ${{ secrets.SP_SUBSCRIPTION_ID }}
          az-client-id: ${{ secrets.SP_APPID }}
          az-secret: ${{ secrets.SP_PASSWORD }}
          az-tenant-id: ${{ secrets.SP_TENANT }}
          az-image: "auto-github-runner:L0BaseImage"
          az-location: "westus"
          az-vm-size: "Standard_D4s_v5"
