# -*- mode: ruby -*-
# vi: set ft=ruby :
#
#  Vagrant-managed VM with Kontain KM / KKM preinstalled.
#

Vagrant.configure(2) do |config|

  config.vm.box = "bento/ubuntu-20.10"

  config.vm.provision "file", source: "../build/kkm.run", destination: "~/kontain/"
  config.vm.provision "file", source: "./daemon.json", destination: "~/kontain/"
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provision "shell", inline: <<-SHELL

   # Install KKM... it will also validate hardware.
   sudo  apt-get install linux-headers-$(uname -r) -y 2>&1
   ./kontain/kkm.run 2>&1

   # Install Docker
   sudo apt-get install -q -y \
         apt-transport-https ca-certificates \
         curl gnupg-agent software-properties-common
   curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -  2>&1

   sudo add-apt-repository \
      "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

   sudo apt-get update -y -q
   sudo apt-get install -y -q docker-ce docker-ce-cli containerd.io

   # Install Kontain. Version is passed to kontain-install.sh
   sudo mkdir -p /opt/kontain ; sudo chown -R $(whoami) /opt/kontain
   wget https://raw.githubusercontent.com/kontainapp/km-releases/master/kontain-install.sh -q
   chmod a+x ./kontain-install.sh; ./kontain-install.sh v0.1-beta2

   # Configure Docker and restart
   sudo  usermod -aG docker vagrant
   sudo cp ./kontain/daemon.json /etc/docker/daemon.json
   sudo systemctl reload-or-restart docker.service

  SHELL

   l=ENV['KM_VAGRANT_PRELOAD_IMAGES']
   if l != nil then
      l.split.each do |image|
         config.vm.provision "shell", inline: "docker pull #{image}"
      end
   end

   config.vm.provider "virtualbox" do |v|
      v.memory = 8182
      v.cpus = 4
   end

   config.vm.post_up_message = "Welcome to Ubuntu with Kontain / KKM preinstalled."
end
