#
#  Copyright © 2021 Kontain Inc. All rights reserved.
#
#  Kontain Inc CONFIDENTIAL
#
#   This file includes unpublished proprietary source code of Kontain Inc. The
#   copyright notice above does not evidence any actual or intended publication of
#   such source code. Disclosure of this source code or any related proprietary
#   information is strictly prohibited without the express written permission of
#   Kontain Inc.
#

# scan all these and  'make' stuff there
SUBDIRS := libkontain

TOP := $(shell git rev-parse --show-toplevel)
include ${TOP}/make/actions.mk
