FROM alpine as app

MAINTAINER "whoever"

RUN apk add py3-pip && pip3 install --upgrade pip

include(Dockerfile.flask.include)

# FROM kontain/python-km:msterin-flask

# COPY copy_all_py.py /tmp
# RUN /kpython copy_all_py.py

# # find out the entry point and insert it here
# # for now add manually
# ENTRYPOINT ["/kpython"]
# CMD ["flask_hello.py"]