#
# Copyright 2021 Kontain Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dweb-deployment
  labels:
    app: dweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dweb
  template:
    metadata:
      labels:
        app: dweb
    spec:
      containers:
      - name: dweb
        image: dweb-km
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
           requests:
              devices.kubevirt.io/kvm: "1"
              cpu: 100m
              memory: "10Mi"
           limits:
              devices.kubevirt.io/kvm: "1"
              cpu: 2
              memory: "500Mi"
        args: [ "8080"]
        volumeMounts:
            - name: kontain-monitor
              mountPath: /opt/kontain
      volumes:
        - name: kontain-monitor
          hostPath:
            path: /opt/kontain

