steps:
  - bash: |
      set -e
      [ "$TRACE" ] && set -x
      make -C tests pull-buildenv-image
      make -j withdocker
      make -C tests testenv-image push-testenv-image
    displayName: KM build - set build environment, build, create test container and push it to registry

  # Orders are important here. We need km built before we build kontaind.
  - bash: |
      make -C cloud/k8s/kontaind/installer push-runenv-image
    displayName: build and push kontaind