# This file should contain all the build steps. This will be shared between
# multiple pipelines to build all the artifacts.

steps:
  - bash: |
      set -e
      [ "$TRACE" ] && set -x
      make -C tests pull-buildenv-image
      make -j withdocker
      make -C km -j withdocker TARGET=coverage
      make -C tests testenv-image push-testenv-image
    displayName: KM build - set build environment, build, create test container and push it to registry

  # Orders are important here. We need km built before we build kontaind.
  - bash: |
      make -C cloud/k8s/kontaind/installer push-runenv-image
    displayName: build and push kontaind

  - bash: |
      make -C cloud/azure ci-prepare-testenv LOCATION=payloads/python
    displayName: Python.km build - set build environment, build, create test container and push it to registry

  - bash: |
      make -C payloads/python build-modules pack-modules MODULES="markupsafe wrapt"
      make -C payloads/python custom CUSTOM_MODULES="markupsafe wrapt"
    displayName: Python.km custom build

  - bash: make -C cloud/azure ci-prepare-testenv LOCATION=payloads/node
    displayName: Node.km build - set build environment, build, create test container and push it to registry

  - bash: make -C cloud/azure ci-prepare-testenv LOCATION=payloads/java
    displayName: Java.kmd build and Java 'runenv' build

  - bash: make -C payloads clean all runenv-image push-demo-runenv-image
    displayName: payload build runenv and demo-runenv images
