#!/bin/bash
# invoke gcc with extra params for Kontain link

TMP_SPEC="/tmp/gcc-${BASHPID}.spec"

function cleanup() {
   rm -rf ${TMP_SPEC}
}

trap cleanup EXIT

cmd=`basename ${BASH_SOURCE[0]}`
dir=`dirname ${BASH_SOURCE[0]}`
KM_TOP=`realpath $dir/..`
PREFIX=/opt/kontain
# check if this is run in local build tree and use the local libs then
if [[ x${KM_TOP} == x${PREFIX}/* ]] ; then
   LIB="-L ${PREFIX}/lib64"
   CRT="${PREFIX}/lib64"
   SPEC="${PREFIX}/lib64"
else
   LIB="-L ${PREFIX}/lib64 -L ${KM_TOP}/build/runtime"
   CRT="${KM_TOP}/build/runtime/musl/crt"
   SPEC="${KM_TOP}"
fi

cat <<EOF > ${TMP_SPEC}
%rename link old_link

*lib:
-lruntime -lpthread -lruntime

*libgcc:
libgcc.a%s %:if-exists(libgcc_eh.a%s)

*startfile:
${CRT}/crt1.o%s ${CRT}/x86_64/crti.o%s crtbeginT.o%s

*endfile:
crtend.o%s ${CRT}/x86_64/crtn.o%s

*link:
%(old_link) -static -Ttext-segment=0x200000 -u__km_sigreturn -u__km_handle_interrupt -u__km_clone_run_child -e_start_c --gc-sections -zseparate-code -znorelro -zmax-page-size=0x1000
EOF

if [[ $cmd == *g++ ]] ; then REALGCC=g++; else REALGCC=gcc; fi
if [[ $# -eq 0 ]] ; then exec "${REALGCC}" ; fi

"${REALGCC}" -static -no-pie -specs=${TMP_SPEC} "$@" ${LIB}

