#!/bin/sh
# see km_elf.h for the list of symbols which need to stay in the stripped executable
exec strip -K __km_handle_interrupt -K __km_interrupt_table -K __km_sigreturn -K __km_syscall_handler "$@"
