name: Run tests
description: Perform all necessary configurations and run tests
inputs:
  kernel:
    description: kvm or kkm - will configure as requested
    required: true
  build-flavor:
    description: coverage or valgrind
    required: false
    default: '' # assumes all

runs:
  using: "composite"
  steps:

    - id: process-inputs
      run: |
        [[ -z "${{inputs.build-flavor}}" ]] && echo "::set-output name=img::" || echo "::set-output name=img::${{inputs.build-flavor}}-"
        [[ "${{inputs.kernel}}" == "kkm" ]] && echo "::set-output name=device::HYPERVISOR_DEVICE=/dev/kkm" || echo "::set-output name=device::"
      shell: bash

    - name: Login to Azure Repository
      run: make -C cloud/azure login-cli
      shell: bash

    - uses: ./.github/actions/configure-kkm
      with:
        build-flavor: valgrind

    - run: |
        if [ "${{inputs.kernel}}" == "kvm" ]
        then
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666"' > /tmp/rules
          sudo mv /tmp/rules /etc/udev/rules.d/99-perm.rules
          sudo udevadm control --reload-rules && sudo udevadm trigger
        fi
      shell: bash

    - name: Pull ${{inputs.build-flavor}} testenv images
      run: make -C tests pull-${{steps.process-inputs.outputs.img}}testenv-image
      shell: bash

    - name: Run ${{inputs.build-flavor}} tests
      run: |
        make -C tests test-${{steps.process-inputs.outputs.img}}withdocker ${{steps.process-inputs.outputs.device}} DOCKER_INTERACTIVE= DOCKER_RUN_CLEANUP=
      shell: bash
