/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_kontain_snapshots_Snapshot */

#ifndef _Included_app_kontain_snapshots_Snapshot
#define _Included_app_kontain_snapshots_Snapshot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_kontain_snapshots_Snapshot
 * Method:    take_native
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_app_kontain_snapshots_Snapshot_take_1native
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
